import type { Metadata } from "next";

import "../globals.css";

;

export const metadata: Metadata = {
  title: "form",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <header>My Website Header</header> */}
        <main>{children}</main>
        {/* <footer>My Website Footer</footer> */}
      </body>
    </html>
  );
}
